package com.sonatype.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "ProductInfo")
public class ProductInfo
{
  private String id;

  private String description;

  private String cost;

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  @DynamoDBAttribute
  public String getDescription() {
    return description;
  }

  @DynamoDBAttribute
  public String getCost() {
    return cost;
  }

  public ProductInfo() {
  }

  public ProductInfo(final String description, final String cost) {
    this.description = description;
    this.cost = cost;
  }

  public void setId(final String id) {
    this.id = id;
  }

  public void setDescription(final String description) {
    this.description = description;
  }

  public void setCost(final String cost) {
    this.cost = cost;
  }

  @Override
  public String toString() {
    return "ProductInfo{" +
        "id='" + id + '\'' +
        ", description='" + description + '\'' +
        ", cost='" + cost + '\'' +
        '}';
  }
}
